POST http://localhost:3333/conta
Content-Type: application/json
// CRIA

{
    "AdicionarValor": 10
}

###

GET  http://localhost:3333/conta

###

PUT http://localhost:3333/conta/
Content-Type: application/json

{
    "AdicionarValor": 144
}

###

DELETE http://localhost:3333/conta/